/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/final_scene.gltf -K 
*/

import { useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";
import { useEffect, useMemo, useRef } from "react";
import {
  useAnimations,
  useGLTF,
  useTexture,
  useVideoTexture,
} from "@react-three/drei";
import { MeshStandardMaterial, SRGBColorSpace } from "three";
import { motion } from "framer-motion-3d";
import { sRGBEncoding } from "@react-three/drei/helpers/deprecated";
import { scale } from "framer-motion";
// import { animate, useMotionValue } from "framer-motion";

export function Final_scene(props) {
  const { section } = props;
  const group = useRef();
  const { scene, animations } = useGLTF("Models/final_scene.gltf");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const texture = useTexture("textures/final_baked.jpg");

  const quoteText = useTexture("textures/Quote.png");
  const textureVdo = useVideoTexture("videos/demo.mp4");
  const textureVdo2 = useVideoTexture("videos/coding.mp4");

  texture.flipY = false;
  quoteText.flipY = true;
  textureVdo.flipY = false;
  textureVdo2.flipY = false;
  // texture.colorSpace = SRGBColorSpace;
  texture.encoding = sRGBEncoding;
  quoteText.colorSpace = SRGBColorSpace;
  textureVdo2.colorSpace = SRGBColorSpace;
  textureVdo.colorSpace = SRGBColorSpace;

  const textureMaterial = new MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="screen_monitor.001"
          geometry={nodes.screen_monitor001.geometry}
          position={[-2.607, 2.152, 0.678]}
          rotation={[-1.57, 0.002, 0.01]}
          scale={0.029}
        >
          <meshBasicMaterial map={textureVdo} toneMapped={false} />
        </mesh>
        <mesh
          name="Object_24001_14"
          geometry={nodes.Object_24001_14.geometry}
          position={[-1.898, 1.686, 0.615]}
          scale={[0.101, 0.161, 0.242]}
        >
          <meshBasicMaterial map={textureVdo2} toneMapped={false} />
        </mesh>
        <mesh
          position={[-2.984, 3.46, 0.67]}
          rotation={[Math.PI / 2, Math.PI / 2, -Math.PI / 2]}
          scale={0.9}
        >
          <planeGeometry args={[1, 1]} />
          <meshBasicMaterial map={quoteText} />
        </mesh>
        {/* <group
          name="Empty"
          position={[-2.057, 2.867, -2.208]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.185, 1.128, 1.185]}
        >
          <group name="Armature" position={[2.288, -1.795, -0.802]}>
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials["Wolf3D_Body.001"]}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Glasses"
            geometry={nodes.Wolf3D_Glasses.geometry}
            material={materials["Wolf3D_Glasses.001"]}
            skeleton={nodes.Wolf3D_Glasses.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials["Wolf3D_Hair.001"]}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials["Wolf3D_Outfit_Bottom.001"]}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials["Wolf3D_Outfit_Footwear.001"]}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials["Wolf3D_Outfit_Top.001"]}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials["Wolf3D_Eye.001"]}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials["Wolf3D_Eye.001"]}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials["Wolf3D_Skin.001"]}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials["Wolf3D_Teeth.001"]}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group> */}
        <group
          name="laptop_tuf"
          position={[-1.898, 1.686, 0.615]}
          scale={[0.101, 0.161, 0.242]}
        >
          <mesh
            name="Object_24001"
            geometry={nodes.Object_24001.geometry}
            material={materials.keyLight}
          />
          <mesh
            name="Object_24001_1"
            geometry={nodes.Object_24001_1.geometry}
            material={materials.DECK}
          />
          <mesh
            name="Object_24001_2"
            geometry={nodes.Object_24001_2.geometry}
            material={materials.deck2}
          />
          <mesh
            name="Object_24001_3"
            geometry={nodes.Object_24001_3.geometry}
            material={materials.pendrive}
          />
          <mesh
            name="Object_24001_4"
            geometry={nodes.Object_24001_4.geometry}
            material={materials.material}
          />
          <mesh
            name="Object_24001_5"
            geometry={nodes.Object_24001_5.geometry}
            material={materials.KEYS}
          />
          <mesh
            name="Object_24001_6"
            geometry={nodes.Object_24001_6.geometry}
            material={materials.wasd_key}
          />
          <mesh
            name="Object_24001_7"
            geometry={nodes.Object_24001_7.geometry}
            material={materials["DECK.001"]}
          />
          <mesh
            name="Object_24001_8"
            geometry={nodes.Object_24001_8.geometry}
            material={materials.material_7}
          />
          <mesh
            name="Object_24001_9"
            geometry={nodes.Object_24001_9.geometry}
            material={materials.power_button}
          />
          <mesh
            name="Object_24001_10"
            geometry={nodes.Object_24001_10.geometry}
            material={materials.tuf_logo}
          />
          <mesh
            name="Object_24001_11"
            geometry={nodes.Object_24001_11.geometry}
            material={materials.display_sqr}
          />
          <mesh
            name="Object_24001_12"
            geometry={nodes.Object_24001_12.geometry}
            material={materials.ASUS_LOGO}
          />
          <mesh
            name="Object_24001_13"
            geometry={nodes.Object_24001_13.geometry}
            material={materials.outer_logo}
          />
          <mesh
            name="Object_24001_14"
            geometry={nodes.Object_24001_14.geometry}
            material={materials.screen}
          />
        </group>
        <group name="sofa" position={[1.04, 0.396, -2.12]}>
          <mesh
            name="Freedom_Sofa_002002"
            geometry={nodes.Freedom_Sofa_002002.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Freedom_Sofa_002002_1"
            geometry={nodes.Freedom_Sofa_002002_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Freedom_Sofa_002002_2"
            geometry={nodes.Freedom_Sofa_002002_2.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="mats"
          geometry={nodes.mats.geometry}
          material={materials.Mousepad}
          position={[-1.115, 0.427, 0.661]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 121.736, 1.322]}
        />
        <mesh
          name="mouse_pad"
          geometry={nodes.mouse_pad.geometry}
          material={textureMaterial}
          position={[-1.878, 1.673, 0.087]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          name="small_mats"
          geometry={nodes.small_mats.geometry}
          material={textureMaterial}
          position={[1, 0.477, -0.951]}
          rotation={[Math.PI, -0.754, Math.PI]}
        />
        <mesh
          name="phone_standing"
          geometry={nodes.phone_standing.geometry}
          material={materials.base}
          position={[-1.872, 1.666, 1.251]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
          scale={[0.058, 0.071, 0.071]}
        />
        <group
          name="phone"
          position={[-1.883, 1.803, 1.251]}
          rotation={[-1.222, -Math.PI / 6, 2.077]}
          scale={0.013}
        >
          <mesh
            name="MobilePhone_Phone_Alpha_0001"
            geometry={nodes.MobilePhone_Phone_Alpha_0001.geometry}
            material={materials["Phone_Alpha.001"]}
          />
          <mesh
            name="MobilePhone_Phone_Alpha_0001_1"
            geometry={nodes.MobilePhone_Phone_Alpha_0001_1.geometry}
            material={materials["Phone_Main.001"]}
          />
          <mesh
            name="MobilePhone_Phone_Alpha_0001_2"
            geometry={nodes.MobilePhone_Phone_Alpha_0001_2.geometry}
            material={materials["Phone_Emission.001"]}
          />
        </group>
        <mesh
          name="monitor_stand"
          geometry={nodes.monitor_stand.geometry}
          material={textureMaterial}
          position={[-2.708, 1.669, 0.656]}
        />
        {/* <mesh
          name="quote"
          geometry={nodes.quote.geometry}
          material={materials["Material.011"]}
          position={[-2.984, 3.46, 0.67]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        /> */}
        <group name="wall_light" position={[-0.418, 3.928, -3.33]}>
          <mesh
            name="Object_1007"
            geometry={nodes.Object_1007.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_1007_1"
            geometry={nodes.Object_1007_1.geometry}
            material={textureMaterial}
          />
        </group>
        <motion.group
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 0.4 : 1.5,
          }}
          name="cute_cat"
          position={[2.786, 0.418, 2.839]}
          rotation={[-Math.PI / 2, 0, 0]}
          // scale={0.434}
        >
          <mesh
            name="Object_0"
            geometry={nodes.Object_0.geometry}
            material={materials.defaultMat_0}
          />
          <mesh
            name="Object_0_1"
            geometry={nodes.Object_0_1.geometry}
            material={materials.defaultMat}
          />
          <mesh
            name="Object_0_2"
            geometry={nodes.Object_0_2.geometry}
            material={materials.material_5}
          />
          <mesh
            name="Object_0_3"
            geometry={nodes.Object_0_3.geometry}
            material={materials.material_4}
          />
          <mesh
            name="Object_0_4"
            geometry={nodes.Object_0_4.geometry}
            material={materials.material_3}
          />
          <mesh
            name="Object_0_5"
            geometry={nodes.Object_0_5.geometry}
            material={materials.material_2}
          />
          <mesh
            name="Object_0_6"
            geometry={nodes.Object_0_6.geometry}
            material={materials.material_1}
          />
          <mesh
            name="Object_0_7"
            geometry={nodes.Object_0_7.geometry}
            material={materials.material_0}
          />
        </motion.group>
        <group
          name="mouse"
          position={[-1.908, 1.675, 0.18]}
          rotation={[0, 1.571, 0]}
          scale={0.015}
        >
          <mesh
            name="BOTON_CENTRAL_MAT_Plastic_0"
            geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry}
            material={materials.MAT_Plastic}
          />
          <mesh
            name="BOTON_CENTRAL_MAT_Plastic_0_1"
            geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_1.geometry}
            material={materials.MAT_Emission}
          />
          <mesh
            name="BOTON_CENTRAL_MAT_Plastic_0_2"
            geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_2.geometry}
            material={materials.MAT_Details}
          />
        </group>
        <group
          name="monitor"
          position={[-2.607, 2.152, 0.678]}
          rotation={[-1.57, 0.002, 0.01]}
          scale={0.029}
        >
          <mesh
            name="group_0_Material001_0"
            geometry={nodes.group_0_Material001_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="group_0_Material001_0_1"
            geometry={nodes.group_0_Material001_0_1.geometry}
            material={materials["material.003"]}
          />
          <mesh
            name="group_0_Material001_0_2"
            geometry={nodes.group_0_Material001_0_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="group_0_Material001_0_3"
            geometry={nodes.group_0_Material001_0_3.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <mesh
          name="chair"
          geometry={nodes.chair.geometry}
          material={materials.None}
          position={[-1.143, 0.775, 1.184]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.08, 0.08, 0.093]}
        />
        <motion.group
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 0.05 : 0.08,
          }}
          name="coffee"
          position={[-1.726, 1.663, 2.081]}
          rotation={[-Math.PI / 2, 0, 0]}
          // scale={0.041}
        >
          <mesh
            name="Object_0007"
            geometry={nodes.Object_0007.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Object_0007_1"
            geometry={nodes.Object_0007_1.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Object_0007_2"
            geometry={nodes.Object_0007_2.geometry}
            material={materials["Material.013"]}
          />
        </motion.group>
        <group
          name="table"
          position={[-2.282, 0.384, 0.646]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            name="Object_0008"
            geometry={nodes.Object_0008.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_1"
            geometry={nodes.Object_0008_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_2"
            geometry={nodes.Object_0008_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_3"
            geometry={nodes.Object_0008_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_4"
            geometry={nodes.Object_0008_4.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_5"
            geometry={nodes.Object_0008_5.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_6"
            geometry={nodes.Object_0008_6.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_7"
            geometry={nodes.Object_0008_7.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0008_8"
            geometry={nodes.Object_0008_8.geometry}
            material={textureMaterial}
          />
        </group>
        <group
          name="lamp"
          position={[-2.766, 1.666, 2.091]}
          rotation={[-Math.PI / 2, 0, 2.094]}
        >
          <mesh
            name="Object_0009"
            geometry={nodes.Object_0009.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0009_1"
            geometry={nodes.Object_0009_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0009_2"
            geometry={nodes.Object_0009_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0009_3"
            geometry={nodes.Object_0009_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Object_0009_4"
            geometry={nodes.Object_0009_4.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="dog_meme"
          geometry={nodes.dog_meme.geometry}
          material={textureMaterial}
          position={[-2.581, 1.742, 1.95]}
          rotation={[0, 1.222, 0]}
        />

        <group name="Plane" position={[0, 0.404, 0]}>
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={textureMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/final_scene.gltf");
useTexture.preload("textures/final_baked.jpg");
