/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/scene.gltf 
*/

import React, { useEffect, useRef } from "react";
import {
  useAnimations,
  useGLTF,
  useTexture,
  useVideoTexture,
} from "@react-three/drei";
import { MeshStandardMaterial, SRGBColorSpace } from "three";
import { sRGBEncoding } from "@react-three/drei/helpers/deprecated";
import { motion } from "framer-motion-3d";
// import { animate, useMotionValue } from "framer-motion";
// import { useFrame } from "@react-three/fiber";

export function My_room1(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("Models/scene7.gltf");
  const group = useRef();

  const texture = useTexture("textures/baked.jpg");
  const textureVdo = useVideoTexture("videos/demo.mp4");

  texture.flipY = true;
  texture.colorSpace = SRGBColorSpace;
  // texture.encoding = sRGBEncoding;

  const textureMaterial = new MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  // ----------debug later----------
  // if (!nodes.screen_monitor) {
  //   console.error("Node 'screen_monitor' not found in GLTF model.");
  //   return null; // Prevent rendering if node is missing
  // }
  // useEffect(() => {
  //   console.log("GLTF Nodes:", Object.keys(nodes));
  // }, [nodes]);

  // useEffect(() => {
  //   console.log("GLTF Nodes:", Object.keys(nodes));
  // }, [nodes]);

  // --------------------------------

  return (
    <group ref={group} {...props} dispose={null}>
      {/* <mesh
        name="screen_monitor"
        geometry={nodes.screen_monitor.geometry}
        position={[-2.607, 2.152, 0.678]}
        rotation={[-1.57, 0.002, 0.01]}
      >
        <meshBasicMaterial map={textureVdo} toneMapped={false} />
      </mesh> */}

      <group
        name="laptop_tuf"
        position={[-1.898, 1.686, 0.615]}
        scale={[0.101, 0.161, 0.242]}
      >
        <mesh
          name="Object_24001"
          geometry={nodes.Object_24001.geometry}
          material={materials.keyLight}
        />
        <mesh
          name="Object_24001_1"
          geometry={nodes.Object_24001_1.geometry}
          material={materials.DECK}
        />
        <mesh
          name="Object_24001_2"
          geometry={nodes.Object_24001_2.geometry}
          material={materials.deck2}
        />
        <mesh
          name="Object_24001_3"
          geometry={nodes.Object_24001_3.geometry}
          material={materials.pendrive}
        />
        <mesh
          name="Object_24001_4"
          geometry={nodes.Object_24001_4.geometry}
          material={materials.material}
        />
        <mesh
          name="Object_24001_5"
          geometry={nodes.Object_24001_5.geometry}
          material={materials.KEYS}
        />
        <mesh
          name="Object_24001_6"
          geometry={nodes.Object_24001_6.geometry}
          material={materials.wasd_key}
        />
        <mesh
          name="Object_24001_7"
          geometry={nodes.Object_24001_7.geometry}
          material={materials["DECK.001"]}
        />
        <mesh
          name="Object_24001_8"
          geometry={nodes.Object_24001_8.geometry}
          material={materials.material_7}
        />
        <mesh
          name="Object_24001_9"
          geometry={nodes.Object_24001_9.geometry}
          material={materials.power_button}
        />
        <mesh
          name="Object_24001_10"
          geometry={nodes.Object_24001_10.geometry}
          material={materials.tuf_logo}
        />
        <mesh
          name="Object_24001_11"
          geometry={nodes.Object_24001_11.geometry}
          material={materials.display_sqr}
        />
        <mesh
          name="Object_24001_12"
          geometry={nodes.Object_24001_12.geometry}
          material={materials.ASUS_LOGO}
        />
        <mesh
          name="Object_24001_13"
          geometry={nodes.Object_24001_13.geometry}
          material={materials.outer_logo}
        />
        <mesh
          name="Object_24001_14"
          geometry={nodes.Object_24001_14.geometry}
          material={materials.material_13}
        />
      </group>
      <group name="sofa" position={[0.243, 0.396, -2.12]} scale={1.569}>
        <mesh
          name="Freedom_Sofa_002002"
          geometry={nodes.Freedom_Sofa_002002.geometry}
          material={materials["Freedom_Sofa_Material.004"]}
        />
        <mesh
          name="Freedom_Sofa_002002_1"
          geometry={nodes.Freedom_Sofa_002002_1.geometry}
          material={materials["Freedom_Sofa_Material.005"]}
        />
        <mesh
          name="Freedom_Sofa_002002_2"
          geometry={nodes.Freedom_Sofa_002002_2.geometry}
          material={materials["Freedom_Sofa_Material.007"]}
        />
      </group>
      <mesh
        name="mats"
        geometry={nodes.mats.geometry}
        material={materials.Mousepad}
        position={[-1.115, 0.427, 0.661]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 121.736, 1.322]}
      />
      <mesh
        name="mouse_pad"
        geometry={nodes.mouse_pad.geometry}
        material={materials["phong1SG.001"]}
        position={[-1.878, 1.673, 0.087]}
        rotation={[0, 1.571, 0]}
        scale={[0.168, 0.273, 0.273]}
      />
      <mesh
        name="small_mats"
        geometry={nodes.small_mats.geometry}
        material={materials.material_1_002}
        position={[0.233, 0.477, -0.951]}
        rotation={[Math.PI, -0.754, Math.PI]}
        scale={1.86}
      />
      <mesh
        name="phone_standing"
        geometry={nodes.phone_standing.geometry}
        material={materials.base}
        position={[-1.872, 1.666, 1.251]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={[0.058, 0.071, 0.071]}
      />
      <group
        name="phone"
        position={[-1.883, 1.803, 1.251]}
        rotation={[-1.222, -Math.PI / 6, 2.077]}
        scale={0.013}
      >
        <mesh
          name="MobilePhone_Phone_Alpha_0001"
          geometry={nodes.MobilePhone_Phone_Alpha_0001.geometry}
          material={materials["Phone_Alpha.001"]}
        />
        <mesh
          name="MobilePhone_Phone_Alpha_0001_1"
          geometry={nodes.MobilePhone_Phone_Alpha_0001_1.geometry}
          material={materials["Phone_Main.001"]}
        />
        <mesh
          name="MobilePhone_Phone_Alpha_0001_2"
          geometry={nodes.MobilePhone_Phone_Alpha_0001_2.geometry}
          material={materials["Phone_Emission.001"]}
        />
      </group>
      <mesh
        name="monitor_stand"
        geometry={nodes.monitor_stand.geometry}
        material={nodes.monitor_stand.material}
        position={[-2.708, 1.669, 0.656]}
      />
      <mesh
        name="quote"
        geometry={nodes.quote.geometry}
        material={materials["Material.011"]}
        position={[-2.984, 3.46, 0.67]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.414}
      />
      <group name="wall_light" position={[-0.418, 3.928, -3.33]} scale={0.002}>
        <mesh
          name="Object_1007"
          geometry={nodes.Object_1007.geometry}
          material={materials["FrontColor.002"]}
        />
        <mesh
          name="Object_1007_1"
          geometry={nodes.Object_1007_1.geometry}
          material={materials["FrontColor.003"]}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 0.4 : 0.5,
        }}
        name="cute_cat"
        position={[2.786, 0.418, 2.839]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Object_0"
          geometry={nodes.Object_0.geometry}
          material={materials.defaultMat_0}
        />
        <mesh
          name="Object_0_1"
          geometry={nodes.Object_0_1.geometry}
          material={materials.defaultMat}
        />
        <mesh
          name="Object_0_2"
          geometry={nodes.Object_0_2.geometry}
          material={materials.material_5}
        />
        <mesh
          name="Object_0_3"
          geometry={nodes.Object_0_3.geometry}
          material={materials.material_4}
        />
        <mesh
          name="Object_0_4"
          geometry={nodes.Object_0_4.geometry}
          material={materials.material_3}
        />
        <mesh
          name="Object_0_5"
          geometry={nodes.Object_0_5.geometry}
          material={materials.material_2}
        />
        <mesh
          name="Object_0_6"
          geometry={nodes.Object_0_6.geometry}
          material={materials.material_1}
        />
        <mesh
          name="Object_0_7"
          geometry={nodes.Object_0_7.geometry}
          material={materials.material_0}
        />
      </motion.group>
      <group
        name="mouse"
        position={[-1.908, 1.675, 0.18]}
        rotation={[0, 1.571, 0]}
        scale={0.015}
      >
        <mesh
          name="BOTON_CENTRAL_MAT_Plastic_0"
          geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry}
          material={materials.MAT_Plastic}
        />
        <mesh
          name="BOTON_CENTRAL_MAT_Plastic_0_1"
          geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_1.geometry}
          material={materials.MAT_Emission}
        />
        <mesh
          name="BOTON_CENTRAL_MAT_Plastic_0_2"
          geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_2.geometry}
          material={materials.MAT_Details}
        />
      </group>
      <group
        name="monitor"
        position={[-2.607, 2.152, 0.678]}
        rotation={[-1.57, 0.002, 0.01]}
        scale={0.029}
      >
        <mesh
          name="group_0_Material001_0"
          geometry={nodes.group_0_Material001_0.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          name="group_0_Material001_0_1"
          geometry={nodes.group_0_Material001_0_1.geometry}
          material={materials["material.003"]}
        />
        <mesh
          name="group_0_Material001_0_2"
          geometry={nodes.group_0_Material001_0_2.geometry}
          material={materials.layar}
        />
        <mesh
          name="group_0_Material001_0_3"
          geometry={nodes.group_0_Material001_0_3.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="group_0_Material001_0_4"
          geometry={nodes.group_0_Material001_0_4.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        name="chair"
        geometry={nodes.chair.geometry}
        material={materials.None}
        position={[-1.243, 0.84, 1.184]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.08, 0.08, 0.093]}
      />
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 0.05 : 0.08,
        }}
        name="coffee"
        position={[-1.726, 1.663, 2.081]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          name="Object_0007"
          geometry={nodes.Object_0007.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          name="Object_0007_1"
          geometry={nodes.Object_0007_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Object_0007_2"
          geometry={nodes.Object_0007_2.geometry}
          material={materials["Material.013"]}
        />
      </motion.group>
      <group
        name="table"
        position={[-2.282, 0.384, 0.646]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.753, 1.753, 1.739]}
      >
        <mesh
          name="Object_0008"
          geometry={nodes.Object_0008.geometry}
          material={materials["comp_desk_c.001"]}
        />
        <mesh
          name="Object_0008_1"
          geometry={nodes.Object_0008_1.geometry}
          material={materials["comp_desk.001"]}
        />
        <mesh
          name="Object_0008_2"
          geometry={nodes.Object_0008_2.geometry}
          material={materials["comp_desk_b.001"]}
        />
        <mesh
          name="Object_0008_3"
          geometry={nodes.Object_0008_3.geometry}
          material={materials["comp_desk_a.001"]}
        />
        <mesh
          name="Object_0008_4"
          geometry={nodes.Object_0008_4.geometry}
          material={materials["comp_desk_remote.001"]}
        />
        <mesh
          name="Object_0008_5"
          geometry={nodes.Object_0008_5.geometry}
          material={materials["comp_desk_2remote.001"]}
        />
        <mesh
          name="Object_0008_6"
          geometry={nodes.Object_0008_6.geometry}
          material={materials["comp_desk_1remote.001"]}
        />
        <mesh
          name="Object_0008_7"
          geometry={nodes.Object_0008_7.geometry}
          material={materials["comp_desk_button.001"]}
        />
        <mesh
          name="Object_0008_8"
          geometry={nodes.Object_0008_8.geometry}
          material={materials["comp_desk_top.001"]}
        />
      </group>
      <group
        position={[-2.766, 1.666, 2.091]}
        rotation={[-Math.PI / 2, 0, 2.094]}
        scale={[0.029, 0.029, 0.031]}
      >
        <mesh
          name="Object_0009"
          geometry={nodes.Object_0009.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          name="Object_0009_1"
          geometry={nodes.Object_0009_1.geometry}
          material={materials.blinn2SG}
        />
        <mesh
          name="Object_0009_2"
          geometry={nodes.Object_0009_2.geometry}
          material={materials.initialShadingGroup}
        />
        <mesh
          name="Object_0009_3"
          geometry={nodes.Object_0009_3.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          name="Object_0009_4"
          geometry={nodes.Object_0009_4.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          name="Object_0009_5"
          geometry={nodes.Object_0009_5.geometry}
          material={materials.phong1SG}
        />
      </group>
      <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 0.1 : 0.15,
        }}
        name="dog_meme"
        geometry={nodes.dog_meme.geometry}
        material={textureMaterial}
        position={[-2.581, 1.742, 1.95]}
        rotation={[0, 1.222, 0]}
      />
      <group name="Plane" position={[0, 0.404, 0]} scale={3}>
        <mesh
          name="Plane_1"
          geometry={nodes.Plane_1.geometry}
          material={materials["Plaster wall.001"]}
        />
        <mesh
          name="Plane_2"
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("Models/scene7.gltf");
useTexture.preload("textures/baked.jpg");
