/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Models/scene.gltf 
*/

import React, { useRef } from "react";
import { useAnimations, useGLTF, useTexture } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import { sRGBEncoding } from "@react-three/drei/helpers/deprecated";

export function My_room(props) {
  const { nodes, materials } = useGLTF("Models/scene4.gltf");
  const group = useRef();
  // const { actions } = useAnimations(animations, group);
  const texture = useTexture("textures/baked1.002.jpg");
  const textureMaterial = new MeshStandardMaterial({
    map: texture,
  });
  texture.flipY = false;
  texture.encoding = sRGBEncoding;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="coffee"
          position={[-1.834, 1.801, 1.725]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.04}
        >
          <group name="Kaffeebecherobjcleanermaterialmergergles">
            <group name="Object_2001" position={[-0.057, 0.005, 1.169]}>
              <mesh
                name="Object_0003"
                geometry={nodes.Object_0003.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                name="Object_0003_1"
                geometry={nodes.Object_0003_1.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                name="Object_0003_2"
                geometry={nodes.Object_0003_2.geometry}
                material={materials["Material.003"]}
              />
            </group>
          </group>
        </group>
        <group name="mats" position={[-0.26, 0.404, 0.529]} scale={1.063}>
          <mesh
            name="Mousepad"
            geometry={nodes.Mousepad.geometry}
            material={materials.Mousepad}
            position={[-0.81, 0.013, 0.137]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 121.736, 1.322]}
          />
        </group>
        <group
          name="small_mat"
          position={[2.665, 1.082, -2.041]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.575}
        >
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="rug5_6" rotation={[Math.PI / 2, 0, 0]}>
                <group name="Geom_5">
                  <group name="export_002_3" rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_6004"
                      geometry={nodes.Object_6004.geometry}
                      material={textureMaterial}
                      position={[-1.505, 0.439, -0.607]}
                      rotation={[Math.PI, -0.754, Math.PI]}
                      scale={1.349}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="phone"
          position={[-1.891, 1.951, 1.262]}
          rotation={[-1.237, -0.516, 2.167]}
          scale={1.575}
        >
          <group
            name="7a704550d49a492d82894e7dfa5d8a9cfbx001"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode002">
              <group name="MobilePhone001">
                <group name="Object_4006" rotation={[-Math.PI / 2, 0, 0]}>
                  <group
                    name="MobilePhone_Phone_Alpha_0001"
                    position={[0.027, -1.741, 2.512]}
                  >
                    <mesh
                      name="MobilePhone_Phone_Alpha_0001_1"
                      geometry={nodes.MobilePhone_Phone_Alpha_0001_1.geometry}
                      material={materials["Phone_Alpha.001"]}
                    />
                    <mesh
                      name="MobilePhone_Phone_Alpha_0001_2"
                      geometry={nodes.MobilePhone_Phone_Alpha_0001_2.geometry}
                      material={materials["Phone_Main.001"]}
                    />
                    <mesh
                      name="MobilePhone_Phone_Alpha_0001_3"
                      geometry={nodes.MobilePhone_Phone_Alpha_0001_3.geometry}
                      material={materials["Phone_Emission.001"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="dog_meme"
          position={[-2.438, 1.869, 2.051]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={0.1}
        >
          <group name="root004">
            <group name="GLTF_SceneRootNode004" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Doggy_0"
                rotation={[-0.114, -0.007, -0.044]}
                scale={0.779}
              >
                <mesh
                  name="mesh_0"
                  geometry={nodes.mesh_0.geometry}
                  material={textureMaterial}
                  morphTargetDictionary={nodes.mesh_0.morphTargetDictionary}
                  morphTargetInfluences={nodes.mesh_0.morphTargetInfluences}
                  position={[-0.06, 1.169, -1.233]}
                  rotation={[-0.191, -1.331, -0.331]}
                  scale={1.391}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="wall_light"
          position={[-1.182, 2.974, -1.564]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group name="wwwobjcleanermaterialmergergles">
            <group
              name="Object_3003"
              position={[500.923, 1173.639, 461.973]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.219}
            >
              <mesh
                name="Object_1007"
                geometry={nodes.Object_1007.geometry}
                material={materials["FrontColor.002"]}
              />
              <mesh
                name="Object_1007_1"
                geometry={nodes.Object_1007_1.geometry}
                material={materials["FrontColor.003"]}
              />
            </group>
            <group
              name="Object_3005"
              position={[1006.771, 1173.639, 461.973]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.219}
            >
              <mesh
                name="Object_1019"
                geometry={nodes.Object_1019.geometry}
                material={materials["FrontColor.002"]}
              />
              <mesh
                name="Object_1019_1"
                geometry={nodes.Object_1019_1.geometry}
                material={materials["FrontColor.003"]}
              />
            </group>
            <group
              name="Object_3006"
              position={[1526.448, 1173.639, 461.973]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.219}
            >
              <mesh
                name="Object_1020"
                geometry={nodes.Object_1020.geometry}
                material={materials["FrontColor.002"]}
              />
              <mesh
                name="Object_1020_1"
                geometry={nodes.Object_1020_1.geometry}
                material={materials["FrontColor.003"]}
              />
            </group>
          </group>
        </group>
        <group
          name="cat_cute"
          position={[2.842, 0.357, -2.294]}
          rotation={[-Math.PI / 2, 0, 1.504]}
          scale={0.39}
        >
          <group name="zbrush_concatosgbcleanermaterialmergergles">
            <group name="models1">
              <group name="Object_5">
                <mesh
                  name="Object_1"
                  geometry={nodes.Object_1.geometry}
                  material={materials.defaultMat}
                />
                <mesh
                  name="Object_1_1"
                  geometry={nodes.Object_1_1.geometry}
                  material={materials.defaultMat_0}
                />
                <mesh
                  name="Object_1_2"
                  geometry={nodes.Object_1_2.geometry}
                  material={materials.material_5}
                />
                <mesh
                  name="Object_1_3"
                  geometry={nodes.Object_1_3.geometry}
                  material={materials.material_4}
                />
                <mesh
                  name="Object_1_4"
                  geometry={nodes.Object_1_4.geometry}
                  material={materials.material_3}
                />
                <mesh
                  name="Object_1_5"
                  geometry={nodes.Object_1_5.geometry}
                  material={materials.material_3}
                />
                <mesh
                  name="Object_1_6"
                  geometry={nodes.Object_1_6.geometry}
                  material={materials.material_1}
                />
                <mesh
                  name="Object_1_7"
                  geometry={nodes.Object_1_7.geometry}
                  material={materials.material_0}
                />
              </group>
            </group>
            <group name="models2" />
            <group name="models3" />
            <group name="models3001" />
            <group name="models4" />
            <group name="models5" />
            <group name="models6" />
            <group name="models7" />
          </group>
        </group>
        <group
          name="mouse"
          position={[-1.827, 1.801, -0.081]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={1.395}
        >
          <group
            name="eabfacf2ef9a4a6eb05118f06a45a572fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode001">
              <group name="Mouse">
                <group name="BOTON_CENTRAL">
                  <group
                    name="BOTON_CENTRAL_MAT_Plastic_0"
                    position={[0, 3.598, 0]}
                  >
                    <mesh
                      name="BOTON_CENTRAL_MAT_Plastic_0_1"
                      geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_1.geometry}
                      material={materials.MAT_Plastic}
                    />
                    <mesh
                      name="BOTON_CENTRAL_MAT_Plastic_0_2"
                      geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_2.geometry}
                      material={materials.MAT_Emission}
                    />
                    <mesh
                      name="BOTON_CENTRAL_MAT_Plastic_0_3"
                      geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0_3.geometry}
                      material={materials.MAT_Details}
                    />
                  </group>
                </group>
                <group name="polySurface2" />
                <group name="polySurface4" />
                <group name="polySurface5" />
              </group>
            </group>
          </group>
        </group>
        <group
          name="lamp1"
          position={[-2.576, 1.715, 2.18]}
          rotation={[-Math.PI / 2, 0, 2.618]}
          scale={0.075}
        >
          <group
            name="Lamp_tobjcleanermaterialmergergles001"
            position={[1.633, 1.965, 1.394]}
            scale={0.456}
          >
            <group name="Object_14003" position={[0, 0, 0.788]}>
              <mesh
                name="Object_12"
                geometry={nodes.Object_12.geometry}
                material={textureMaterial}
              />
              <mesh
                name="Object_12_1"
                geometry={nodes.Object_12_1.geometry}
                material={textureMaterial}
              />
              <mesh
                name="Object_12_2"
                geometry={nodes.Object_12_2.geometry}
                material={textureMaterial}
              />
              <mesh
                name="Object_12_3"
                geometry={nodes.Object_12_3.geometry}
                material={textureMaterial}
              />
              <mesh
                name="Object_12_4"
                geometry={nodes.Object_12_4.geometry}
                material={textureMaterial}
              />
            </group>
          </group>
        </group>
        <group
          name="computer_table"
          position={[-0.259, 1.513, 1.89]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <group name="root005">
            <group name="GLTF_SceneRootNode005" rotation={[Math.PI / 2, 0, 0]}>
              <group name="comp_desk_0001" rotation={[Math.PI / 2, 0, 0]}>
                <group
                  name="Object_4"
                  position={[1.225, -1.95, 1.116]}
                  scale={1.972}
                >
                  <mesh
                    name="Object_0002"
                    geometry={nodes.Object_0002.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_1"
                    geometry={nodes.Object_0002_1.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_2"
                    geometry={nodes.Object_0002_2.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_3"
                    geometry={nodes.Object_0002_3.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_4"
                    geometry={nodes.Object_0002_4.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_5"
                    geometry={nodes.Object_0002_5.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_6"
                    geometry={nodes.Object_0002_6.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_7"
                    geometry={nodes.Object_0002_7.geometry}
                    material={textureMaterial}
                  />
                  <mesh
                    name="Object_0002_8"
                    geometry={nodes.Object_0002_8.geometry}
                    material={textureMaterial}
                  />
                </group>
              </group>
              <group
                name="comp_desk_remote_1001"
                rotation={[Math.PI / 2, 0, 0]}
              />
              <group name="comp_desk_top_2001" />
            </group>
          </group>
        </group>
        <group
          name="chair"
          position={[-1.013, 0.854, 1.491]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        >
          <group name="Chairobjcleanermaterialmergergles">
            <mesh
              name="Object_2"
              geometry={nodes.Object_2.geometry}
              material={materials["None.001"]}
            />
          </group>
        </group>
        <group
          name="laptop_tuf"
          position={[-0.654, 1.917, 0.514]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.452}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="backlight_19"
                position={[-2.42, 0.02, 0.005]}
                scale={[0.229, 0.346, 0.625]}
              >
                <group name="Object_47">
                  <mesh
                    name="Object_24002"
                    geometry={nodes.Object_24002.geometry}
                    material={materials["keyLight.001"]}
                  />
                  <mesh
                    name="Object_24002_1"
                    geometry={nodes.Object_24002_1.geometry}
                    material={materials["DECK.002"]}
                  />
                  <mesh
                    name="Object_24002_2"
                    geometry={nodes.Object_24002_2.geometry}
                    material={materials["deck2.001"]}
                  />
                  <mesh
                    name="Object_24002_3"
                    geometry={nodes.Object_24002_3.geometry}
                    material={materials["pendrive.001"]}
                  />
                  <mesh
                    name="Object_24002_4"
                    geometry={nodes.Object_24002_4.geometry}
                    material={materials["material.001"]}
                  />
                  <mesh
                    name="Object_24002_5"
                    geometry={nodes.Object_24002_5.geometry}
                    material={materials["display_sqr.001"]}
                  />
                  <mesh
                    name="Object_24002_6"
                    geometry={nodes.Object_24002_6.geometry}
                    material={materials["KEYS.001"]}
                  />
                  <mesh
                    name="Object_24002_7"
                    geometry={nodes.Object_24002_7.geometry}
                    material={materials["wasd_key.001"]}
                  />
                  <mesh
                    name="Object_24002_8"
                    geometry={nodes.Object_24002_8.geometry}
                    material={materials["DECK.003"]}
                  />
                  <mesh
                    name="Object_24002_9"
                    geometry={nodes.Object_24002_9.geometry}
                    material={materials["material_7.001"]}
                  />
                  <mesh
                    name="Object_24002_10"
                    geometry={nodes.Object_24002_10.geometry}
                    material={materials["power_button.001"]}
                  />
                  <mesh
                    name="Object_24002_11"
                    geometry={nodes.Object_24002_11.geometry}
                    material={materials["tuf_logo.001"]}
                  />
                  <mesh
                    name="Object_24002_12"
                    geometry={nodes.Object_24002_12.geometry}
                    material={materials["ASUS_LOGO.001"]}
                  />
                  <mesh
                    name="Object_24002_13"
                    geometry={nodes.Object_24002_13.geometry}
                    material={materials["outer_logo.001"]}
                  />
                  <mesh
                    name="Object_24002_14"
                    geometry={nodes.Object_24002_14.geometry}
                    material={materials["material_13.001"]}
                  />
                </group>
              </group>
              <group
                name="DECK_8"
                position={[-2.302, 0, 0.011]}
                scale={[0.463, 0.024, 0.645]}
              >
                <group
                  name="keys_phy_0"
                  position={[-0.001, 1.102, 0.679]}
                  rotation={[0, -1.571, 0]}
                  scale={[-0.041, -0.088, -0.057]}
                />
                <group
                  name="mold_1_1"
                  position={[-0.977, -0.059, -0.116]}
                  rotation={[Math.PI, 0, Math.PI]}
                  scale={[1, 1.167, 1]}
                />
                <group
                  name="mold_3001_3"
                  position={[-0.91, 0.296, 0.653]}
                  scale={[2.161, 45.815, 0.787]}
                />
                <group
                  name="mold_3_2"
                  position={[-0.91, 0.285, -0.625]}
                  scale={[2.161, 45.815, 0.787]}
                />
                <group
                  name="notification_led_4"
                  position={[-0.917, 1.045, -0.002]}
                  scale={[2.161, 41.868, 1.551]}
                />
                <group
                  name="powerbutton001_6"
                  position={[-0.706, 1.045, -0.934]}
                  scale={[0.036, 0.026, 0.026]}
                >
                  <group
                    name="powerbutton_5"
                    position={[-0.254, 1.368, -0.004]}
                    rotation={[0, 1.571, 0]}
                    scale={[12.048, 1609.138, 57.751]}
                  >
                    <mesh
                      name="Object_22"
                      geometry={nodes.Object_22.geometry}
                      material={materials["material_7.001"]}
                    />
                  </group>
                </group>
                <group
                  name="tufLogo_7"
                  position={[0.492, 0.898, -0.097]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={[-2.161, -41.868, -1.551]}
                />
              </group>
              <group
                name="laptop_display_18"
                position={[-2.734, 0.008, 0.655]}
                rotation={[-Math.PI, 0, 1.136]}
                scale={[-0.762, -0.008, -0.762]}
              >
                <group
                  name="Cylinder001_14"
                  position={[0, 1.111, -1.668]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[-100.103, -1.441, -1.005]}
                />
                <group
                  name="Cylinder_13"
                  position={[0, 1.111, -0.029]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[-100.103, -1.441, -1.005]}
                />
                <group
                  name="Plane_15"
                  position={[0.133, -2.677, -0.77]}
                  rotation={[Math.PI, 0, 0.231]}
                  scale={[-1.472, -130.758, -1.313]}
                />
                <group
                  name="tufLogo001_16"
                  position={[0.992, -3.737, -0.305]}
                  rotation={[-3.142, 0, -0.132]}
                  scale={[1.982, 162.831, 1.718]}
                />
                <group
                  name="wallpaper_17"
                  position={[0.699, -3.434, -0.852]}
                  rotation={[1.575, 1.562, 1.557]}
                  scale={[-0.948, -94.428, -1.008]}
                />
              </group>
              <group
                name="W_12"
                position={[-2.428, 0.03, 0.43]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.039, 0.024, 0.032]}
              >
                <group
                  name="A_9"
                  position={[-1.498, -0.016, 2.039]}
                  scale={[0.652, 0.652, 0.785]}
                />
                <group
                  name="D_10"
                  position={[2.033, 0.003, 2.066]}
                  scale={[0.294, 0.294, 0.354]}
                />
                <group
                  name="S_11"
                  position={[0.229, -0.004, 2.073]}
                  scale={[0.371, 0.371, 0.447]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model"
          position={[-1.879, 1.848, 1.261]}
          rotation={[-Math.PI / 2, 0, 2.078]}
          scale={0.082}
        >
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="STAND_0" scale={[0.827, 1, 1]}>
                <mesh
                  name="Object_4001"
                  geometry={nodes.Object_4001.geometry}
                  material={materials["base.001"]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="monitor"
          position={[-2.691, 2.05, 0.772]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <group name="monitorfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group
                name="SketchUp"
                position={[2.803, -38.914, -25.18]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.464}
              >
                <group name="group_0" position={[2.722, 0.301, 10.79]}>
                  <group name="group_0_Material001_0" position={[0, 0, 1.186]}>
                    <mesh
                      name="group_0_Material001_0_1"
                      geometry={nodes.group_0_Material001_0_1.geometry}
                      material={materials["Material.005"]}
                    />
                    <mesh
                      name="group_0_Material001_0_2"
                      geometry={nodes.group_0_Material001_0_2.geometry}
                      material={materials["material.003"]}
                    />
                    <mesh
                      name="group_0_Material001_0_3"
                      geometry={nodes.group_0_Material001_0_3.geometry}
                      material={materials.layar}
                    />
                    <mesh
                      name="group_0_Material001_0_4"
                      geometry={nodes.group_0_Material001_0_4.geometry}
                      material={materials["Material.006"]}
                    />
                    <mesh
                      name="group_0_Material001_0_5"
                      geometry={nodes.group_0_Material001_0_5.geometry}
                      material={materials["Material.008"]}
                    />
                  </group>
                </group>
                <group name="group_0001" position={[2.442, 6.74, 10.749]} />
                <group name="group_0002" position={[3.567, -0.002, 11.668]} />
              </group>
              <group
                name="SketchUp001"
                position={[0.878, -35.716, -9.286]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.464}
              />
              <group
                name="SketchUp002"
                position={[0.878, -35.716, -9.286]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.464}
              />
              <group
                name="SketchUp003"
                position={[3.454, 183.431, -24.237]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.464}
              />
              <group
                name="SketchUp004"
                position={[0.878, -35.716, -9.286]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={27.464}
              />
            </group>
          </group>
        </group>
        <mesh
          name="Object_22001"
          geometry={nodes.Object_22001.geometry}
          material={materials.material_7}
        />
        <group name="sofa" position={[0.243, 0.396, -2.12]} scale={1.569}>
          <mesh
            name="Freedom_Sofa_002002"
            geometry={nodes.Freedom_Sofa_002002.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Freedom_Sofa_002002_1"
            geometry={nodes.Freedom_Sofa_002002_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Freedom_Sofa_002002_2"
            geometry={nodes.Freedom_Sofa_002002_2.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="mouse_pad"
          geometry={nodes.mouse_pad.geometry}
          material={textureMaterial}
          position={[-1.82, 1.851, -0.103]}
          rotation={[0, 1.571, 0]}
          scale={[0.196, 0.273, 0.273]}
        />
        <mesh
          name="monitor_stand"
          geometry={nodes.monitor_stand.geometry}
          material={nodes.monitor_stand.material}
          position={[-2.708, 1.842, 0.656]}
        />
        <mesh
          name="quote"
          geometry={nodes.quote.geometry}
          material={textureMaterial}
          position={[-2.984, 3.46, 0.67]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.414}
        />
        <group name="Plane" position={[0, 0.404, 0]} scale={3}>
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={materials["default"]}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials.floor1}
          />
          <mesh
            name="Plane_3"
            geometry={nodes.Plane_3.geometry}
            material={nodes.Plane_3.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("Models/scene4.gltf");
